### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by soktherat** [davidsdearaujo/tabbar#1]
The argument type 'PageController' can't be assigned to the parameter type 'TabbarController'.

Undefined class 'TabbarController'.

I need to import 'package:tabbar/src/tabbar_controller.dart';
Please export it.

**Comment by aleonnet** [comment]
Hi @davidsdearaujo ,
I was trying to check upon your approach but got this error.
<<
  type 'PageController' is not a subtype of the type 'TabbarController'
>>

I think you need to change on the code FROM final controller = PageController TO final controller = TabbarController

Thanks
