### ISSUE TITLE
 type 'PageController' is not a subtype of the type 'TabbarController'

### ISSUE THREAD

**Issue by aleonnet** [davidsdearaujo/tabbar#2]
Hi @davidsdearaujo ,
I was trying to check upon your approach but got this error. I can't figure how to solve it out.

  type 'PageController' is not a subtype of the type 'TabbarController'

Thank you.

**Comment by davidsdearaujo** [comment]
Hi @aleonnet ,

Use the factory `TabbarController.fromPageController(PageController controller) `

**Comment by DjordjeMancic97** [comment]
I have the same issue, that factory is not working either. 
Undefined name 'TabbarController'.
Try correcting the name to one that is defined, or defining the name.

**Comment by horppe** [comment]
Hi @davidsdearaujo ,

I am facing the same issue. I tried your suggestion and i still got the error.

**Comment by siman302** [comment]
I tried your suggestion and I got that error.

**Comment by sohaibaslam127** [comment]
> Hi @aleonnet ,
> 
> Use the factory `TabbarController.fromPageController(PageController controller) `

I tried your suggestion but still got that error.
